### ISSUE TITLE
Crash when saving a schematic with the Bundled Origin feature

### ISSUE THREAD

**Issue by maruohon** [Ivan-1F/tweakerplus#3]
I've gotten a couple of issue reports of Litematica crashing when trying to save a schematic. It was tracked down to happening with this mod. So I went looking through your code, and apparently there is just one inverted if check (or rather a missed `!`):

https://github.com/Ivan-1F/tweakerplus/blob/db3eb438723882cc3aaba1757df59a44263c2882/src/main/java/me/ivan1f/tweakerplus/mixins/tweaks/bundleOriginInSchematic/LitematicaSchematicMixin.java#L35

**Comment by Ivan-1F** [comment]
oops, my bad. I'll fix that

**Comment by Ivan-1F** [comment]
Released: https://github.com/Ivan-1F/tweakerplus/releases/tag/v1.0.2
