### ISSUE TITLE
Feature request: Subtitle scaling

### ISSUE THREAD

**Issue by ghost** [Ivan-1F/tweakerplus#4]
Hello, nicee mod 🥰
I would love to scale the Subtitles - similar to "**playerListScale**".
EDIT: Maybe the same for F3 screen as new option, if possible 😊
Greetings.

**Comment by Ivan-1F** [comment]
v1.3.0 will be released with some other features later, you can try `subtitlesScale` and `debugHudScale` with the latest builds from github actions: https://github.com/Ivan-1F/tweakerplus/actions

**Comment by ghost** [comment]
Hello Ivan, thank you so much! I was testing it right now, everything is perfect.
