### ISSUE TITLE
Feature request: Two more scaling options

### ISSUE THREAD

**Issue by ghost** [Ivan-1F/tweakerplus#5]
Hello Ivan 😊
I was thinking about two other scaling options.
The tooltip from items and the items in your main/off hand.
Greetings.

**Comment by Ivan-1F** [comment]
You can fetch the latest build from Github actions: https://github.com/Ivan-1F/tweakerplus/actions

It contains a new MC Tweak: `itemTooltipScale`

However, scaling the item in hand can cause consistency problems when the player is eating, drinking or doing other actions, as well as when the player is holding a map or a crossbow. Mojang handles these rendering logic separately, so it is hard to deal with. This may be implemented later

**Comment by ghost** [comment]
Thanks for your hard work Ivan ❤️

**Comment by ghost** [comment]
I think the Shulker Box rendering is special, it isn't affected from the scaling option.
I use Shulker Box mods - is that important?
EDIT: The same with Ender Chest - I think every container is affected (Bundles?).

![2022-11-19_19 28 09](https://user-images.githubusercontent.com/75373609/202866108-d4472e34-d037-43b9-8c84-c6efacee2da0.png)

**Comment by ghost** [comment]
When I compare two items, it gets back to the normal render size.
The mod: https://www.curseforge.com/minecraft/mc-mods/equipment-compare-fabric
I have this mod as well installed, but I think it has nothing to do with it:
https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

![2022-11-19_20 03 42](https://user-images.githubusercontent.com/75373609/202867315-bba7e1e1-c72a-438d-a2f4-4a749118029f.png)

**Comment by Ivan-1F** [comment]
equipment-compare-fabric and shulker box mods implement the tooltip rendering themselves, which cannot be uniformly handled by tweakerplus

**Comment by ghost** [comment]
Oh darn, maybe I can lead this to the other devs and they want to implement a fix for this. At least the container rendering is really annoying and makes this rule almost obsolete.
