### ISSUE TITLE
Update to 1.19.3 Please

### ISSUE THREAD

**Issue by sternschnaube** [Ivan-1F/tweakerplus#6]

**Comment by Ivan-1F** [comment]
You can get the build for 1.19.3 here: https://github.com/Ivan-1F/tweakerplus/actions/runs/3765870031

**Comment by venaminecraft** [comment]
Thank you Ivan 💖

**Comment by voidrinix** [comment]
> You can get the build for 1.19.3 here: https://github.com/Ivan-1F/tweakerplus/actions/runs/3765870031

Hello! Could you please upload this release to modrinth so that I can add it in my modpack?

**Comment by Ivan-1F** [comment]
> > You can get the build for 1.19.3 here: https://github.com/Ivan-1F/tweakerplus/actions/runs/3765870031
> 
> Hello! Could you please upload this release to modrinth so that I can add it in my modpack?

Published: https://modrinth.com/mod/tweakerplus/version/mc1.19.3-v1.3.1

**Comment by sternschnaube** [comment]
Thank you so much, as always 😊❤️
